#!/usr/bin/env python3

import cgi;

#Debugging output
import cgitb

#Send errors to browser
cgitb.enable

#Print HTML MIME-TYPE header
print ('Content-type:text/html\n')
print()
html ='<!DOCTYPE html>\n'
html += '<html>\n'
html += '<head>\n'
html += '<meta charset="utf-8">\n'
html += '<title>RGR3 Genome Browser</title>\n'

#css stylesheet
html += '<link type="text/css" rel="stylesheet" href="http://student.cryst.bbk.ac.uk/~sr002/css/codon.css">\n'
html += '</head>\n\n'
html += '<body>\n'

#Create table, title
html += '<table>\n'
html += '<caption>CODON USAGE IN HOMO SAPIENS CHROMOSOME 3</caption>\n'
html += '<tr>\n'
#...and coloumn headings
html += '<th> </th>\n'
html += '<th>Codon</th>\n'
html += '<th>Amino Acid</th>\n'
html += '<th>%</th>\n'
html += '<th>Ratio</th>\n'
html += '<th>Codon</th>\n'
html += '<th>Amino Acid</th>\n'
html += '<th>%</th>\n'
html += '<th>Ratio</th>\n'
html += '<th>Codon</th>\n'
html += '<th>Amino Acid</th>\n'
html += '<th>%</th>\n'
html += '<th>Ratio</th>\n'
html += '<th>Codon</th>\n'
html += '<th>Amino Acid</th>\n'
html += '<th>%</th>\n'
html += '<th>Ratio</th>\n'
html += '<th> </th>\n'
html += '</tr>\n'

#Create table row 1 UUU,UCU,UAU,UGU
html += '<tr>\n'
html += '<td class="ucag"><b>U</b></td>\n'
html += '<td rowspan="2">UUU</td>\n'
html += '<td rowspan="2">Phe(F)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">UCU</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">UAU</td>\n'
html += '<td rowspan="2">Tyr(Y)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">UGU</td>\n'
html += '<td rowspan="2">Cys(C)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>U</b></td>\n'
html += '</tr>\n'

#create table row 1a UUU,UCU,UAU,UGU
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 2 UUC,UCC,UAC,UGC
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">UUC</td>\n'
html += '<td rowspan="2">Phe(F)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">UCC</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">UAC</td>\n'
html += '<td rowspan="2">Tyr(Y)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">UGC</td>\n'
html += '<td rowspan="2">Cys(C)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>C</b></td>\n'
html += '</tr>\n'

#create table row 2a UUC,UCC,UAC,UGC
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 3 UUA,UCA,UAA,UGA
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">UUA</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">UCA</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2" class="red">UAA</td>\n'
html += '<td rowspan="2" class="red">STOP</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2" class="red">UGA</td>\n'
html += '<td rowspan="2" class="red">STOP</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>A</b></td>\n'
html += '</tr>\n'

#create table row 3a UUA,UCA,UAA,UGA
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 4 UUG,UCG,UAG,UGG
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">UUG</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">UCG</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2" class="red">UAG</td>\n'
html += '<td rowspan="2" class="red">STOP</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">UGG</td>\n'
html += '<td rowspan="2">Trp(W)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>G</b></td>\n'
html += '</tr>\n'

#create table row 4a UUG,UCG,UAG,UGG
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 5 CUU,CCU,CAU,CGU
html += '<tr>\n'
html += '<td class="ucag"><b>C</b></td>\n'
html += '<td rowspan="2">CUU</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CCU</td>\n'
html += '<td rowspan="2">Pro(P)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CAU</td>\n'
html += '<td rowspan="2">His(H)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CGU</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>U</b></td>\n'
html += '</tr>\n'

#create table row 5a CUU,CCU,CAU,CGU
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 6 CUC,CCC,CAC,CGC
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">CUC</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CCC</td>\n'
html += '<td rowspan="2">Pro(P)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CAC</td>\n'
html += '<td rowspan="2">His(H)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CGC</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>C</b></td>\n'
html += '</tr>\n'

#create table row 6a CUC,CCC,CAC,CGC
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 7 CUA,CCA,CAA,CGA
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">CUA</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CCA</td>\n'
html += '<td rowspan="2">Pro(P)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CAA</td>\n'
html += '<td rowspan="2">Glu(Q)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CGA</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>A</b></td>\n'
html += '</tr>\n'

#create table row 7a CUA,CCA,CAA,CGA
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 8 CUG,CCG,CAG,CGG
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">CUG</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CCG</td>\n'
html += '<td rowspan="2">Pro(P)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CAG</td>\n'
html += '<td rowspan="2">Glu(Q)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">CGG</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>G</b></td>\n'
html += '</tr>\n'

#create table row 8a CUG,CCG,CAG,CGG
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 9 AUU,ACU,AAU,AGU
html += '<tr>\n'
html += '<td class="ucag"><b>A</b></td>\n'
html += '<td rowspan="2">AUU</td>\n'
html += '<td rowspan="2">Ile(I)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">ACU</td>\n'
html += '<td rowspan="2">Thr(T)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">AAU</td>\n'
html += '<td rowspan="2">Asn(N)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">AGU</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>U</b></td>\n'
html += '</tr>\n'

#create table row 9a AUU,ACU,AAU,AGU
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 10 AUC,ACC,AAC,AGC
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">AUC</td>\n'
html += '<td rowspan="2">Ile(I)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">ACC</td>\n'
html += '<td rowspan="2">Thr(T)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">AAC</td>\n'
html += '<td rowspan="2">Asn(N)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">AGC</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>C</b></td>\n'
html += '</tr>\n'

#create table row 10a AUC,ACC,AAC,AGC
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 11 AUA,ACA,AAA,AGA
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">AUA</td>\n'
html += '<td rowspan="2">Ile(I)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">ACA</td>\n'
html += '<td rowspan="2">Thr(T)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">AAA</td>\n'
html += '<td rowspan="2">Lys(K)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">AGA</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>A</b></td>\n'
html += '</tr>\n'

#create table row 11a AUA,ACA,AAA,AGA
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 12 AUG,ACG,AAG,AGG
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2" class="blue">AUG</td>\n'
html += '<td rowspan="2" class="blue">Met(M)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2" class="2">ACG</td>\n'
html += '<td rowspan="2" class="2">Thr(T)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">AAG</td>\n'
html += '<td rowspan="2">Lys(K)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">AGG</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>G</b></td>\n'
html += '</tr>\n'

#create table row 12a AUG,ACG,AAG,AGG
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 13 GUU,GCU,GAU,GGU
html += '<tr>\n'
html += '<td class="ucag"><b>G</b></td>\n'
html += '<td rowspan="2">GUU</td>\n'
html += '<td rowspan="2">Val(V)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GCU</td>\n'
html += '<td rowspan="2">Ala(A)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GAU</td>\n'
html += '<td rowspan="2">Asp(D)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GGU</td>\n'
html += '<td rowspan="2">Gly(G)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>U</b></td>\n'
html += '</tr>\n'

#create table row 13a GUU,GCU,GAU,GGU
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 14 GUC,GCC,GAC,GGC
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">GUC</td>\n'
html += '<td rowspan="2">Val(V)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GCC</td>\n'
html += '<td rowspan="2">Ala(A)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GAC</td>\n'
html += '<td rowspan="2">Asp(D)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GGC</td>\n'
html += '<td rowspan="2">Gly(G)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>C</b></td>\n'
html += '</tr>\n'

#create table row 14a GUC,GCC,GAC,GGC
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 15 GUA,GCA,GAA,GGA
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">GUA</td>\n'
html += '<td rowspan="2">Val(V)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GCA</td>\n'
html += '<td rowspan="2">Ala(A)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GAA</td>\n'
html += '<td rowspan="2">Glu(E)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GGA</td>\n'
html += '<td rowspan="2">Gly(G)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>A</b></td>\n'
html += '</tr>\n'

#create table row 15a GUA,GCA,GAA,GGA
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 16 GUG,GCG,GAG,GGG
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">GUG</td>\n'
html += '<td rowspan="2">Val(V)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GCG</td>\n'
html += '<td rowspan="2">Ala(A)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GAG</td>\n'
html += '<td rowspan="2">Glu(E)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td rowspan="2">GGG</td>\n'
html += '<td rowspan="2">Gly(G)</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td><b>G</b></td>\n'
html += '</tr>\n'

#create table row 16a GUG,GCG,GAG,GGG
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#crreate table bottom row
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td class="center" colspan="4"><b>U</b></td>\n'
html += '<td class="center" colspan="4"><b>C</b></td>\n'
html += '<td class="center" colspan="4"><b>A</b></td>\n'
html += '<td class="center" colspan="4"><b>G</b></td>\n'
html += '<td> </td>\n'
html += '</table>\n'

#Create table explanation
       #<ul>
        #<li>The data shown in the table above is from GenBank</li>
        #<li>The letter in parenthesis represents the one-letter code for the amino acid.</li>
        #<li>% Represents the average frequency this codon is used per 100 codons.</li>
        #<li>Ratio represnts the abundance of that codon realtive to all of the codons for that particular amino acid.</li>
       #</ul>

html += '</body>\n'
html += '</html>\n'

print(html)


                                                                                                                                                                                          649,0-1       Bot
