#!/usr/bin/env python3
#file for codon table 
import cgi;

#Debugging output
import cgitb

#Send errors to browser
cgitb.enable	

#Print HTML MIME-TYPE header
print ('Content-type:text/html\n')
print()
html ='<!DOCTYPE html>\n'
html += '<html>\n'
html += '<head>\n'
html += '<meta charset="utf-8">\n' 
html += '<title>RGR3 Genome Browser</title>\n'

#css stylesheet - note the full URL necessary due to cgi-wrap
html += '<link type="text/css" rel="stylesheet" href="http://student.cryst.bbk.ac.uk/~sr002/css/codonform.css">\n'
html += '</head>\n\n'
html += '<body>\n'

#Create table, title
html += '<table>\n'
html += '<caption>COMAPARISON OF CODON USAGE IN HOMO SAPIENS CHROMOSOME 3 AND SEARCHED GENE</caption>\n'
html += '<tr>\n'
#...and coloumn headings
html += '<th> </th>\n'
html += '<th>Codon</th>\n'
html += '<th>Amino Acid</th>\n'
html += '<th>%</th>\n'
html += '<th>Ratio</th>\n'
html += '<th>Codon</th>\n'
html += '<th>Amino Acid</th>\n'
html += '<th>%</th>\n'
html += '<th>Ratio</th>\n'
html += '<th>Codon</th>\n'
html += '<th>Amino Acid</th>\n'
html += '<th>%</th>\n'
html += '<th>Ratio</th>\n'
html += '<th>Codon</th>\n'
html += '<th>Amino Acid</th>\n'
html += '<th>%</th>\n'
html += '<th>Ratio</th>\n'
html += '<th> </th>\n'
html += '</tr>\n'

#Create table row 2 UUU,UCU,UAU,UGU
html += '<tr>\n'
html += '<td class="ucag"><b>U</b></td>\n'
html += '<td rowspan="2">UUU</td>\n'
html += '<td rowspan="2">Phe(F)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">UCU</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">UAU</td>\n'
html += '<td rowspan="2">Tyr(Y)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">UGU</td>\n'
html += '<td rowspan="2">Cys(C)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>U</b></td>\n'
html += '</tr>\n'

#create table row 3 UUU,UCU,UAU,UGU
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 4 UUC,UCC,UAC,UGC
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">UUC</td>\n'
html += '<td rowspan="2">Phe(F)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">UCC</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">UAC</td>\n'
html += '<td rowspan="2">Tyr(Y)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">UGC</td>\n'
html += '<td rowspan="2">Cys(C)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>C</b></td>\n'
html += '</tr>\n'

#create table row 5 UUC,UCC,UAC,UGC
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 6 UUA,UCA,UAA,UGA
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">UUA</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">UCA</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2" class="red">UAA</td>\n'
html += '<td rowspan="2" class="red">STOP</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2" class="red">UGA</td>\n'
html += '<td rowspan="2" class="red">STOP</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>A</b></td>\n'
html += '</tr>\n'

#create table row 7 UUA,UCA,UAA,UGA
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 8 UUG,UCG,UAG,UGG
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">UUG</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">UCG</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2" class="red">UAG</td>\n'
html += '<td rowspan="2" class="red">STOP</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">UGG</td>\n'
html += '<td rowspan="2">Trp(W)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>G</b></td>\n'
html += '</tr>\n'

#create table row 9 UUG,UCG,UAG,UGG
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 10 CUU,CCU,CAU,CGU
html += '<tr>\n'
html += '<td class="ucag"><b>C</b></td>\n'
html += '<td rowspan="2">CUU</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CCU</td>\n'
html += '<td rowspan="2">Pro(P)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CAU</td>\n'
html += '<td rowspan="2">His(H)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CGU</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>U</b></td>\n'
html += '</tr>\n'

#create table row 11 CUU,CCU,CAU,CGU
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 12 CUC,CCC,CAC,CGC
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">CUC</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CCC</td>\n'
html += '<td rowspan="2">Pro(P)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CAC</td>\n'
html += '<td rowspan="2">His(H)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CGC</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>C</b></td>\n'
html += '</tr>\n'

#create table row 13 CUC,CCC,CAC,CGC
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 14 CUA,CCA,CAA,CGA
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">CUA</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CCA</td>\n'
html += '<td rowspan="2">Pro(P)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CAA</td>\n'
html += '<td rowspan="2">Glu(Q)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CGA</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>A</b></td>\n'
html += '</tr>\n'

#create table row 15 CUA,CCA,CAA,CGA
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 16 CUG,CCG,CAG,CGG
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">CUG</td>\n'
html += '<td rowspan="2">Leu(L)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CCG</td>\n'
html += '<td rowspan="2">Pro(P)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CAG</td>\n'
html += '<td rowspan="2">Glu(Q)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">CGG</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>G</b></td>\n'
html += '</tr>\n'

#create table row 17 CUG,CCG,CAG,CGG
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 18 AUU,ACU,AAU,AGU
html += '<tr>\n'
html += '<td class="ucag"><b>A</b></td>\n'
html += '<td rowspan="2">AUU</td>\n'
html += '<td rowspan="2">Ile(I)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">ACU</td>\n'
html += '<td rowspan="2">Thr(T)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">AAU</td>\n'
html += '<td rowspan="2">Asn(N)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">AGU</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>U</b></td>\n'
html += '</tr>\n'

#create table row 19 AUU,ACU,AAU,AGU
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 20 AUC,ACC,AAC,AGC
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">AUC</td>\n'
html += '<td rowspan="2">Ile(I)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">ACC</td>\n'
html += '<td rowspan="2">Thr(T)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">AAC</td>\n'
html += '<td rowspan="2">Asn(N)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">AGC</td>\n'
html += '<td rowspan="2">Ser(S)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>C</b></td>\n'
html += '</tr>\n'

#create table row 21 AUC,ACC,AAC,AGC
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 22 AUA,ACA,AAA,AGA
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">AUA</td>\n'
html += '<td rowspan="2">Ile(I)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">ACA</td>\n'
html += '<td rowspan="2">Thr(T)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">AAA</td>\n'
html += '<td rowspan="2">Lys(K)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">AGA</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>A</b></td>\n'
html += '</tr>\n'

#create table row 23 AUA,ACA,AAA,AGA
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 24 AUG,ACG,AAG,AGG
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2" class="blue">AUG</td>\n'
html += '<td rowspan="2" class="blue">Met(M)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2" class="2">ACG</td>\n'
html += '<td rowspan="2" class="2">Thr(T)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">AAG</td>\n'
html += '<td rowspan="2">Lys(K)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">AGG</td>\n'
html += '<td rowspan="2">Arg(R)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>G</b></td>\n'
html += '</tr>\n'

#create table row 25 AUG,ACG,AAG,AGG
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 26 GUU,GCU,GAU,GGU
html += '<tr>\n'
html += '<td class="ucag"><b>G</b></td>\n'
html += '<td rowspan="2">GUU</td>\n'
html += '<td rowspan="2">Val(V)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GCU</td>\n'
html += '<td rowspan="2">Ala(A)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GAU</td>\n'
html += '<td rowspan="2">Asp(D)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GGU</td>\n'
html += '<td rowspan="2">Gly(G)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>U</b></td>\n'
html += '</tr>\n'

#create table row 27 GUU,GCU,GAU,GGU
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 28 GUC,GCC,GAC,GGC
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">GUC</td>\n'
html += '<td rowspan="2">Val(V)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GCC</td>\n'
html += '<td rowspan="2">Ala(A)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GAC</td>\n'
html += '<td rowspan="2">Asp(D)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GGC</td>\n'
html += '<td rowspan="2">Gly(G)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>C</b></td>\n'
html += '</tr>\n'

#create table row 29 GUC,GCC,GAC,GGC
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 30 GUA,GCA,GAA,GGA
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">GUA</td>\n'
html += '<td rowspan="2">Val(V)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GCA</td>\n'
html += '<td rowspan="2">Ala(A)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GAA</td>\n'
html += '<td rowspan="2">Glu(E)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GGA</td>\n'
html += '<td rowspan="2">Gly(G)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>A</b></td>\n'
html += '</tr>\n'

#create table row 31 GUA,GCA,GAA,GGA
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#Create table row 32 GUG,GCG,GAG,GGG
html += '<tr>\n'
html += '<td class="ucag"> </td>\n'
html += '<td rowspan="2">GUG</td>\n'
html += '<td rowspan="2">Val(V)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GCG</td>\n'
html += '<td rowspan="2">Ala(A)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GAG</td>\n'
html += '<td rowspan="2">Glu(E)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td rowspan="2">GGG</td>\n'
html += '<td rowspan="2">Gly(G)</td>\n'
html += '<td><b>%</b></td>\n'
html += '<td class="ratio"><b>ratio</b></td>\n'
html += '<td><b>G</b></td>\n'
html += '</tr>\n'

#create table row 33 GUG,GCG,GAG,GGG
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td>%</td>\n'
html += '<td class="ratio">ratio</td>\n'
html += '<td> </td>\n'
html += '</tr>\n'

#create table bottom row
html += '<tr>\n'
html += '<td> </td>\n'
html += '<td class="center" colspan="4"><b>U</b></td>\n'
html += '<td class="center" colspan="4"><b>C</b></td>\n'
html += '<td class="center" colspan="4"><b>A</b></td>\n'
html += '<td class="center" colspan="4"><b>G</b></td>\n'
html += '<td> </td>\n'
html += '</table>\n'

#Create table explanation in unordered list
html += '<ul>\n'
html +=	'<li>The data shown in the table above is from GenBank</li>\n'
html += '<li>The letter in parenthesis represents the one-letter code for the amino acid.</li>\n'
html += '<li>The below % Represents the average frequency this codon is used per 100 codons in homo sapiens chromosome 3.</li>\n'
html += '<li>The above % Represents the average frequency this codon is used per 100 codons in the searched gene.</li>\n'
html += '<li>The below ratio represents the abundance of that codon relative to all of the codons for that particular amino acid in homo sapiens chromosome 3.</li>\n'
html += '<li>The above ratio represents the abundance of that codon relative to all of the codons for that particular amino acid in the searched gene.</li>\n'
html += '</ul>\n'
	
html += '</body>\n'
html += '</html>\n'

print(html)


                                                                                                                                  649,0-1       Bot
